import { Geist, Geist_Mono, Rubik } from "next/font/google";

// Global CSS
import "./globals.css";

// Componnets
import Navbar from "./components/Navbar";

// // About Fonts
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
// // About Fonts
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
// // My fonts
const rubik = Rubik({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`
          ${rubik.variable} 
          antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
